name = "belead-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2025-03-16"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "c81a668b71372c891ecaf3e8a78e1d2b"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"                     # Identifiant unique de cette migration
new_sqlite_classes = ["ChatRoom"]  # Votre classe Durable Object

[[services]]
binding = "API"
service = "belead-api"

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`
